### ISSUE TITLE
Sphereon (App Store) 

### ISSUE THREAD

**Issue by ssi-vc-dev** [Sphereon-Opensource/mobile-wallet#182]
Hello guys. 

I can see that the published Sphereon Wallet on the App Store was updated 5 months ago, and you have had many updates on the develop branch in the last few days. 

Do you maybe have a branch (or reference to a commit) of the version that is published on the App Store?

Thanks!

**Comment by sanderPostma** [comment]
@ssi-vc-dev 
We are currently working to release new versions for both Android and iOS, with the latter still requiring some work. We expect them to be rolled out in the coming days.

**Comment by sanderPostma** [comment]
@ssi-vc-dev
Concerning the current release, the build is from October 2nd, the commit would be 2fc08341ddc78ec5a16bf6715749b0d6aa2d2d23
But if you are using a recent version of our libraries like OID4VCI and SSI-SDK there will be incompatibilities with the October version of the wallet app.

**Comment by ssi-vc-dev** [comment]
Okay, clear. Thanks! @sanderPostma
