### ISSUE TITLE
Mobile Wallet does not load after latest update (version 0.2.0)

### ISSUE THREAD

**Issue by flarocca** [Sphereon-Opensource/mobile-wallet#184]
I was using the mobile app in a Samsung Galaxy S23 Ultra, but since version 0.2.0 it just stopped working. It didn't crash, it just doesn't load no matter how much time I wait

The only context I can provide is the app version, as I can't find any log info nor report.

I am using the app for learning and testing purposes, since I am building my own Identity provider supporting OIDC and OIDC4VC, OIDCVCI and SIOP

**Comment by nklomp** [comment]
Hi @flarocca could you delete the data from the wallet?

We are still at a 0.x version,  and we had to use a new secure key value store and database driver. I think this might be causing issues in your case.

Just use a long press on the wallet icon and then go to storage. Of course that will delete credentials from your wallet unfortunately

**Comment by flarocca** [comment]
I see, I completely understand it is a Beta, I am also building a Proof of
Concept, so no worries for that and thank you very much for responding.

I tried clearing cache and data, I even uninstalled the app, nothing
happened.
I tried another device, and the same.

Thanks a lot!

**Comment by nklomp** [comment]
Thanks for reporting.  Okay that must be the new database driver. We had something similar in the past when moving from react-native-sqlite to expo-sqlite. But then we could reproduce it on multiple devices during testing. I will release an updated version tomorrow

On 12 Apr 2024 19:13, Facundo La Rocca ***@***.***> wrote:

I see, I completely understand it is a Beta, I am also building a Proof of
Concept, so no worries for that and thank you very much for responding.

I tried clearing cache and data, I even uninstalled the app, nothing
happened.
I tried another device, and the same.

Thanks a lot!

**Comment by flarocca** [comment]
Hi Niels! Just double checking if the release could move forward!
Thanks

**Comment by nklomp** [comment]
Yes we are testing. Expect to offer it to Android/Apple today


Met vriendelijke groet,


Niels Klomp

CTO



[cid:75fa796d-bf16-46d2-83a3-84af6e21a782]


J.M. Keynesplein 10
1066 EP Amsterdam

+31 (0)852 736513

Op woensdagmiddag niet aanwezig


***@***.***?anonymous&ep=signature>             Maak een afspraak voor een gesprek met ***@***.***?anonymous&ep=signature>
________________________________
Van: Facundo La Rocca ***@***.***>
Verzonden: dinsdag 16 april 2024 07:56
Aan: Sphereon-Opensource/mobile-wallet ***@***.***>
CC: Niels Klomp ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [Sphereon-Opensource/mobile-wallet] Mobile Wallet does not load after latest update (version 0.2.0) (Issue #184)


Hi Niels! Just double checking if the release could move forward!
Thanks

**Comment by flarocca** [comment]
That's awesome Nels! Thank you very much!
I would be glad to help by beta testing if you guys need help!

Btw, is there a way I can check app's logs for debugging purposes? It would greatly help me

**Comment by flarocca** [comment]
@nklomp , I've seen the commit woth the fix has been merged. Do you have an idea when it will be released to the App Store (Android and Apple)

Thanks a lot!

**Comment by flarocca** [comment]
@nklomp I just saw the release and tested the new version! The issue is completely solved!
Thank you so much!

Note: on version `0.2.0` the wallet accepted uris running over plain `http`, which was super helpful for local development. On the new version that is no longer possible, making local development almost impossible.
